# Generated by Django 5.1.2 on 2024-10-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bio', 'Bio waste'), ('glass', 'Glass'), ('plastic', 'Plastic')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storage')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='StorageCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField()),
                ('current_capacity', models.IntegerField(default=0)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storage')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wastetype')),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='waste_types',
            field=models.ManyToManyField(through='core.StorageCapacity', to='core.wastetype'),
        ),
    ]
